apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-app

spec:
  containers:
    - name: postgres
      image: postgres:9.4
      data:
       POSTGRES_DB: votedbdb
       POSTGRES_USER: postgresadmin
       POSTGRES_PASSWORD: admin123
      ports:
        - containerPort: 5432
